#!/bin/sh

# PROVIDE: ddserver
# REQUIRE: LOGIN
# KEYWORD: shutdown

. /etc/rc.subr

name="ddserver"
rcvar=ddserver_enable
load_rc_config $name

ddserver_enable=${ddserver_enable:-"NO"}
ddserver_user=${ddserver_user:-"www"}

pidfile=/var/run/ddserver.pid

procname="/usr/local/bin/ddserver-bundle"
command="/usr/sbin/daemon -P ${pidfile} -f ${procname}"

start_cmd="${name}_start"
stop_cmd="${name}_stop"
status_cmd="${name}_status"

ddserver_start()
{
  ${command}
}

ddserver_stop()
{
  [ -f ${pidfile} ] && kill `cat ${pidfile}`
}

ddserver_status()
{
  [ -f ${pidfile} ] && echo "${name} is running as pid `cat ${pidfile}`."
}

run_rc_command "$1"
